language: c
# Select Trusty Tahr.
sudo: required
dist: trusty
# Travis' git submodule support is ... broken? half-broken? Maybe intentional?
git:
  submodules: false
  depth: 3
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq libssl-dev libgcrypt20-dev libpurple-dev libwebp-dev
script: ./configure $CONFIGURE_FLAGS && make
compiler:
  - clang
  - gcc
env:
# Try to be nice to the builder
  - CONFIGURE_FLAGS=""
  - CONFIGURE_FLAGS="--disable-gcrypt"
  - CONFIGURE_FLAGS="                 --disable-libwebp"
#  - CONFIGURE_FLAGS="--disable-gcrypt --disable-libwebp"
  - CONFIGURE_FLAGS="                                   --disable-translation"
#  - CONFIGURE_FLAGS="--disable-gcrypt                   --disable-translation"
#  - CONFIGURE_FLAGS="                 --disable-libwebp --disable-translation"
  - CONFIGURE_FLAGS="--disable-gcrypt --disable-libwebp --disable-translation"
