language: c
git:
  submodules: false
  depth: 3
before_install:
  - git submodule update --init --recursive
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgcrypt20-dev libssl-dev libpurple-dev libwebp-dev
script: ./configure && make
compiler:
  - clang
  - gcc
